/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.NumericBadConsequence;
import NapakalakiGame.SpecificBadConsequence;

/**
 *
 * @author antonio
 */
public class BadConsequenceView extends javax.swing.JPanel {

    private BadConsequence badConsequence;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }
    
    public void setBadConsequence(BadConsequence b){
        badConsequence = b;
        
        Class clase = b.getClass();
        String nombre = clase.getSimpleName();
        texto.setText(badConsequence.getText());
        String aux = "Niveles perdidos " + badConsequence.getLevels();
        niveles.setText(aux);
        
        if(!badConsequence.isEmpty() && nombre.equals("SpecificBadConsequence")){
            
            aux = " " + ((SpecificBadConsequence) badConsequence).getSpecificvisibleTreasure();
            specificV.setText(aux);
            aux = " " + ((SpecificBadConsequence) badConsequence).getSpecificHiddenTreasure();
            specificH.setText(aux);
            cantidadTesorosH.setText(" ");
            cantidadTesorosV.setText(" ");
        }
        else if(!badConsequence.isEmpty() && nombre.equals("NumericBadConsequence")){
            aux = "Ocultos: " + ((NumericBadConsequence) badConsequence).getHiddenTreasures();
            cantidadTesorosH.setText(aux);
            aux = "Visibles: " + ((NumericBadConsequence) badConsequence).getVisibleTreasures();
            cantidadTesorosV.setText(aux);
            specificV.setText(" ");
            specificH.setText(" ");
            
        }
            repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JLabel();
        niveles = new javax.swing.JLabel();
        cantidadTesorosV = new javax.swing.JLabel();
        cantidadTesorosH = new javax.swing.JLabel();
        specificV = new javax.swing.JLabel();
        specificH = new javax.swing.JLabel();

        texto.setText("texto");

        niveles.setText("niveles");

        cantidadTesorosV.setText("cantidadTesorosV");

        cantidadTesorosH.setText("cantidadTesorosH");

        specificV.setText("specificV");

        specificH.setText("specificH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specificH)
                    .addComponent(niveles)
                    .addComponent(texto)
                    .addComponent(cantidadTesorosV)
                    .addComponent(cantidadTesorosH)
                    .addComponent(specificV))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto)
                .addGap(18, 18, 18)
                .addComponent(niveles)
                .addGap(18, 18, 18)
                .addComponent(cantidadTesorosV)
                .addGap(18, 18, 18)
                .addComponent(cantidadTesorosH)
                .addGap(18, 18, 18)
                .addComponent(specificV)
                .addGap(18, 18, 18)
                .addComponent(specificH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantidadTesorosH;
    private javax.swing.JLabel cantidadTesorosV;
    private javax.swing.JLabel niveles;
    private javax.swing.JLabel specificH;
    private javax.swing.JLabel specificV;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
