/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.CombatResult;
import NapakalakiGame.Monster;
import NapakalakiGame.Napakalaki;
import NapakalakiGame.Player;
import javax.swing.JButton;

/**
 *
 * @author antonio
 */
public class NapakalakiView extends javax.swing.JFrame {

    private Napakalaki NapakalakiModel;
    private Player currentPlayer;
    private Monster currentMonster;
    boolean pasarTurno = false;
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
       
    }
    

    
    // Método que da valor al atributo privado NapakalakiModel
    public void setNapakalaki(Napakalaki npk){
        this.currentMonster=npk.getCurrentMonster();
        this.currentPlayer=npk.getCurrentPlayer();
        this.NapakalakiModel=npk;
        this.playerView1.setNapakalaki(npk, this);
        this.playerView1.setPlayer(currentPlayer);
        
        if(this.MeetTheMonster.isEnabled() && this.combat.isEnabled() && this.NextTurn.isEnabled()){
            // Esto quiere decir que es la primera partida. Desactiva los botones correspondientes
            this.combat.setEnabled(false);
            this.NextTurn.setEnabled(false);
        }
        repaint();
        revalidate();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultado = new javax.swing.JLabel();
        MeetTheMonster = new javax.swing.JButton();
        combat = new javax.swing.JButton();
        NextTurn = new javax.swing.JButton();
        monsterView1 = new GUI.MonsterView();
        playerView1 = new GUI.PlayerView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultado.setText("resultado");

        MeetTheMonster.setText("Monstruo");
        MeetTheMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeetTheMonsterActionPerformed(evt);
            }
        });

        combat.setText("Combatir");
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });

        NextTurn.setText("Siguiente Turno");
        NextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextTurnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(542, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MeetTheMonster)
                        .addGap(18, 18, 18)
                        .addComponent(combat)
                        .addGap(18, 18, 18)
                        .addComponent(NextTurn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultado)
                            .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resultado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MeetTheMonster)
                    .addComponent(combat)
                    .addComponent(NextTurn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MeetTheMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeetTheMonsterActionPerformed
        this.MeetTheMonster.setEnabled(false); // Boton a false
        this.combat.setEnabled(true);
        monsterView1.setMonster(currentMonster);
        playerView1.botones(true);
        repaint();
        revalidate();
        
    }//GEN-LAST:event_MeetTheMonsterActionPerformed

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
        this.combat.setEnabled(false);
        Boolean fin = false; // Para indicar el final de la partida
        CombatResult resultado = NapakalakiModel.developCombat(); // Desarrollo de combate
        if(resultado.equals(CombatResult.LOSE))
            this.resultado.setText("Has perdido");
        else if(resultado.equals(CombatResult.LOSEANDCONVERT)){
            this.resultado.setText("Te conviertes");
        }
        else if(resultado.equals(CombatResult.WIN))
            this.resultado.setText("Has ganado el combate");
        else{
            fin=true;
            this.resultado.setText("Has ganado la partida");
        }
        this.setNapakalaki(NapakalakiModel);
        
        if(fin)
            System.exit(0); // Termina la partida
        pasarTurno=true;
        this.activarSiguienteTurno(); // Activa el boton si se puede pasar de turno
    }//GEN-LAST:event_combatActionPerformed
    public void activarSiguienteTurno(){
        if(currentPlayer.validState() && pasarTurno && currentPlayer.getHiddenTreasures().size() < 5 && !MeetTheMonster.isEnabled() &&
                !combat.isEnabled())
            this.NextTurn.setEnabled(true);
        else
            playerView1.pintarMalaConsecuencia();
    }
    private void NextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextTurnActionPerformed
        if(NapakalakiModel.nextTurn()){
            this.setNapakalaki(NapakalakiModel);
            this.NextTurn.setEnabled(false);
            this.combat.setEnabled(false);
            this.MeetTheMonster.setEnabled(true);
            pasarTurno=false;
        }
        
    }//GEN-LAST:event_NextTurnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MeetTheMonster;
    private javax.swing.JButton NextTurn;
    private javax.swing.JButton combat;
    private GUI.MonsterView monsterView1;
    private GUI.PlayerView playerView1;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
