/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Treasure;
import java.awt.Color;

/**
 *
 * @author antonio
 */
public class TreasureView extends javax.swing.JPanel {

    // tesoro para representar visualmente
    private Treasure treasureModel;
    private Boolean selected;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        this.selected = false;
        initComponents();
    }
    
    // Método que devuelve el tesoro
    public Treasure getTreasure(){
        return treasureModel;
    }
    
    // Método que actualiza el tesoro
    public void setTreasure(Treasure copia){
        treasureModel = new Treasure(copia);
        
        this.nombre.setText(treasureModel.getName());
        this.tipo.setText(treasureModel.getTextType());
        this.bonus.setText(treasureModel.getTextBonus());
        
        repaint();
       
    }

    // Método de consulta del atributo selected
    public Boolean isSelected(){
        
        return selected;
    }
    
   
    // Método que da color al fondo si recibe true
    public void setOpaque(Boolean estado){
        if(estado)
            this.setBackground(Color.blue);
        else
            this.setBackground(Color.GREEN);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        bonus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(118, 147, 206));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        nombre.setText("nombre");

        tipo.setText("tipo");

        bonus.setText("bonus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bonus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bonus)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected; // Si estaba seleccionado se pone a no seleccionado y viceversa
        
        this.setOpaque(selected);
    }//GEN-LAST:event_formMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonus;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
